fix(server): generate plate using core utils
Qbox-project/qb-vehicleshop pull request #24
Opened 2023-07-04 12:03 UTC by skizmx

## Description
- generate plate using core utils

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My code fits the style guidelines.
- [x] My PR fits the contribution guidelines.

2023-07-04 12:09 UTC, BerkieBb commented
We have a `GenerateRandomPlate` function there

2023-07-04 12:11 UTC, BerkieBb commented
https://github.com/Qbox-project/qbx-core/blob/main/modules/utils.lua#L143
`GenerateRandomPlate('11AAA111')` This is to generate a random plate according to the default GTA 5 pattern

2023-07-04 12:38 UTC, BerkieBb approved these changes

2023-07-04 19:37 UTC, Manason requested changes

2023-07-04 19:37 UTC, Manason commented on server.lua
> +        TriggerClientEvent('qb-vehicleshop:client:TestDrive', target, { vehicle = vehicle })
Why change the parameter to a table of only one value?

2023-07-14 14:35 UTC, Manason approved these changes

2023-07-14 15:41 UTC, merged