refactor: finance menu and vehicle display
Qbox-project/qb-vehicleshop pull request #49
Opened 2023-12-13 02:12 UTC by MafewTM

## Description

- Remove the chosenVehicle config entry and rename defaultVehicle to vehicle
- Adjust the config tables to be more readable
- Remove the two step opening process for opening the finance menu
- Rework how the information is displayed in the menu
- Add a confirmation check when paying off a vehicle in full
- Slight adjustment to the testDrive code and DrawText2D positioning
- Change default test drive time from 30 seconds to 5 minutes before despawning

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2023-12-13 17:24 UTC, Manason approved these changes

2023-12-21 16:56 UTC, solareon requested changes

2023-12-21 16:56 UTC, solareon commented on client/main.lua
Rather than hard coding the text prompts we should have them be locale based to allow for easier translations

2023-12-21 17:37 UTC, MafewTM commented on client/main.lua
Yep. The plan is to go through all the locales once we're done refactoring and remove/add what needs to be removed/added

2023-12-21 18:15 UTC, solareon commented on client/main.lua
aight. fair enough.

2023-12-21 18:16 UTC, solareon approved these changes

2023-12-21 18:17 UTC, merged