Swap vehicle model check.
Qbox-project/qb-vehicleshop pull request #58
Opened 2024-02-01 13:39 UTC by Randolio

This adds a check to make sure the model you are trying to swap to exists/streamed before making the swap. Without this, if you have a "vehicle364" (which isn't streamed) as the example model you are trying to swap to, it will delete the previous vehicle and attempt to load the new one and fail, making it so you can not interact with the vehicle in that particular spot unless you relog.

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2024-02-01 17:31 UTC, Manason requested changes

2024-02-01 17:31 UTC, Manason commented on client/main.lua
> +        print(('Failed to find model for "%s". Vehicle might not be streamed?'):format(data.toVehicle))
```suggestion
        lib.print.error(('Failed to find model for "%s". Vehicle might not be streamed?'):format(data.toVehicle))
```

2024-02-02 13:48 UTC, Randolio reviewed
Good?

2024-02-03 12:03 UTC, BerkieBb approved these changes

2024-02-03 17:04 UTC, Manason approved these changes

2024-02-07 05:02 UTC, merged