Translation to pt-br and loadmodel for low specs
Qbox-project/qb-vehicleshop pull request #73
Opened 2024-05-22 01:45 UTC by mur4i

## Description

Translation to pt-br and loadmodel for low specs

## Checklist

- [ ] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [ ] My pull request fits the contribution guidelines & code conventions.

2024-05-22 19:14 UTC, BerkieBb requested changes
Change the IsPedInAnyVehicle checks to `cache.vehicle` and the dead checks to the dead check export, `exports.qbx_medical:isDead()`

2024-05-23 13:12 UTC, ArturMichalak commented on client/main.lua
> +    lib.requestModel(model, 5000)
Perhabs may be worth use requestModelTimeout

2024-05-23 13:12 UTC, ArturMichalak commented on client/main.lua
> +        header = 'Espere um minuto!',
These are not language files. The default language for prompts is English.
If you want to translate this messages, create keys in locales/en.json and locales/es.json.

2024-05-23 13:12 UTC, ArturMichalak commented on client/main.lua
> +    while not NetworkGetEntityFromNetworkId(netId) do Wait(100) end
lib.waitFor should be better option

2024-05-23 13:12 UTC, ArturMichalak commented on locales/pt-br.json
> +
```suggestion

```

2024-05-23 13:12 UTC, ArturMichalak commented on locales/pt-br.json
> +
the last line should be empty

2024-05-24 05:44 UTC, ArturMichalak requested changes

2024-05-24 05:44 UTC, ArturMichalak commented on client/main.lua
> -        header = 'Wait a minute!',
These are not language files. The default language for prompts is English.
If you want to translate this messages, create keys in locales/en.json and locales/es.json.

2024-06-19 21:14 UTC, closed without merging

2024-06-19 21:14 UTC, Manason commented
Closing as author has not been responsive. Feel free to re-open.